// Root layout: wraps every page in AuthProvider (starts empty, never fetches), Navbar and Footer.

import "./globals.css";
import { AuthProvider } from "./_context/AuthContext";
import Navbar from "./_layout/Navbar";
import Footer from "./_layout/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
